filter:
    excluded_paths:
        - 'vendor/*'
        - 'js/jquery*'
        - 'js/handlebars*'
        - 'js/backbone*'
        - 'l10n/*'

imports:
    - javascript
    - php

tools:
    external_code_coverage:
        timeout: 1200 # Timeout in seconds. 20 minutes
