sudo: required
dist: trusty
language: php
php:
  - 5.6
  - 7.0

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
    - php5-pgsql

services:
  - docker
  - postgresql

env:
  global:
  - CORE_BRANCH=master
  - TEST_JS=FALSE
  - PHP_COVERAGE=FALSE
  - PACKAGE=FALSE
  - NIGHTLY=FALSE
  - secure: "NETkiOX9vfzvLHINqlaZVCdtPB/HNN2d9I7kVTBZq+cu8/T25aHOdBk7zJktjeFZAt49EMd/w47rsnONf0mLD7RB7/X5LEpi7AiW/1OvL9C6e/TQ9AqB5e49VZzxEdmZKmSByqd3R7p4SDXjdilE0u9UO/waqex4bDYFZ2M0wu5SH8JC3QmV8qLVnT/E3SnXxu/dvfAXMQO2U9r1tEK+09uD1Q9bOg/Igp6D79gsQ1p/CQ9Uvq8xpRVeI9IcFX5Q0//FWzOD3zy6SugQwFiDtMmorC13jQj1aCaQVdLA/h8FTcfnjNY5RAsJEaZVfGMvzb7J+jm9e3EE8QDb/MaS5prKz8Wl1PwNXmkF2icaTqN3Rpq1g4PicNKepVA2pSyr5TkpAMUpApZzXQmTV311bGcpZoO51vlQL+tyDtVxILs8XdTpd/t6PdYYPH5fZDuE0DiwExpIdDDacz4N0LSmBP6ZsqV11ZXwACWcozi3XMnME+KDh8SeclI6tEjj1rOCAv7WBez8cHNSQdATNbyQ8MIV2xJJ3T86vj7sHanT6LQiArEN00BwQj11y2CQf2HqkRGOeu7wtHWYn8pyglvR80r8VGj6EfgshNjU/C6Q0Rm2pMA22S44BQzDV+He7es0KeFqOKVb9eBYudNUxmb+XAFWhRui95M1uGfLiNGzMAA="
  - secure: "N5ce58pppbOna8TCb/0PxZdc63/OpzfXUipfkozybQIl9K7Y8jLPwI0J/ZkMHNJMUtMdV6O8D2YsJAM/9SOlzoPV9nsoc+f6lKYSH4LkAkcGUbP9Zi8M1YRL4tq3t6jVcTCzLzd09PJxgnvcpAxsRmBp/HKgPeH6GcaqddeseIIjT4Oko7ekNwiNzs4H8Sy6cdibFKvQDdADdm6QsropW3BkICWcNvU9Zk+d10QbyKUxbWM7KaxIIh7MOgv3h1894DXkhZfNxKCi+C4lY9y7YfhRVfU7gh2ilWQPaG8gv193k4wsdqkyydazvzqza7IomgIAoyEEWJcHUHIGjeSOwXI/WwFpIfvFxLA6erOhQd6n4rdis9YfPsaY9sP5xALpJVzxAWYH8s1Z9K+G2P+g0h66y/ANv/tY4dQvuXwBHfio3DnvVAdLl9ukMWrd8FuxLG2n8LynFt/Emr/k6kv8r/itS3RV0YGVqqiWZTeHkVfr/LMbkQBZi4XGajSmrCS8NpmhJwr117X9oSFlCg7GcCjKbbQIOAQ2pIq7w/av/p7XCjDHTqEWZ8MsaMEPekf+Vx2oIbTNd8m/aw02nvosnDAYLrfj5ApCZvZCRM10oiIxaQcle1cgYmJCujMsbvIOxog62TXrJ4yyv9E42qRioiq1d1QkEDlvORsN9l+a3Q8="
  matrix:
  - DB=sqlite

branches:
  only:
  - master
  - "/^stable\\d+(\\.\\d+)?$/"
  - /^v\d++(\.\d+)?+(\.\d+)?+(\.\d+)?$/

cache:
  directories:
  - "$HOME/.composer/cache/files"
  - "$HOME/.npm"
  - "$HOME/.cache/bower"

before_install:
  - php --info

  # Set up DB
  - if [[ "$DB" == 'pgsql' ]]; then createuser -U travis -s oc_autotest; fi
  - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e 'create database oc_autotest;'; fi
  - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e "CREATE USER 'oc_autotest'@'localhost' IDENTIFIED BY '';"; fi
  - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e "GRANT ALL ON oc_autotest.* TO 'oc_autotest'@'localhost';"; fi

  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '5.4' ]; then curl -s -o $HOME/.phpenv/versions/5.4/bin/phpunit
    https://phar.phpunit.de/phpunit-4.8.9.phar; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '5.4' ]; then chmod +x $HOME/.phpenv/versions/5.4/bin/phpunit;
    fi"
  - composer self-update
  - make install-composer-deps
  - make start-imap-docker
  - cd ..
  - git clone https://github.com/nextcloud/server.git --recursive --depth 1 -b $CORE_BRANCH core
  - mv mail core/apps/

before_script:
  # Set up core
  - php -f core/occ maintenance:install --database-name oc_autotest --database-user oc_autotest --admin-user admin --admin-pass admin --database $DB --database-pass=''

  # Set up app
  - php -f core/occ app:enable mail
  # Enable app twice to check occ errors of registered commands
  - php -f core/occ app:enable mail
  - cd core/apps/mail
  - sh -c "if [ '$TEST_JS' = 'TRUE' ]; then npm install -g npm@latest; fi"
  - sh -c "if [ '$TEST_JS' = 'TRUE' ]; then make dev-setup; fi"

  # Prepare IMAP test docker
  - make add-imap-account

  # XDebug is only needed if we report coverage -> speeds up other builds
  - if [[ "$PHP_COVERAGE" = "FALSE" ]]; then phpenv config-rm xdebug.ini; fi

script:
  # Check PHP syntax errors
  - find . -name \*.php -not -path './vendor/*' -exec php -l "{}" \;

  # Run server's app code checker
  - php ../../occ app:check-code mail

  # Run JS tests
  - sh -c "if [ '$TEST_JS' = 'TRUE' ]; then grunt; fi"
  - sh -c "if [ '$TEST_JS' = 'TRUE' ]; then cat ./coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js; fi"

  # Run PHP tests
  - cd tests
  - phpunit --configuration phpunit.xml
  - if [[ "$PHP_COVERAGE" = "TRUE" ]]; then wget https://scrutinizer-ci.com/ocular.phar;
    fi
  - if [[ "$PHP_COVERAGE" = "TRUE" ]]; then php ocular.phar code-coverage:upload --format=php-clover
    clover.xml; fi

  # Test packaging
  - cd ..
  - if [[ "$PACKAGE" = "TRUE" ]]; then make appstore; fi

  # Upload the nightly to ftp server
  - if [[ "$NIGHTLY" = "TRUE" ]]; then curl --ftp-create-dirs -T build/artifacts/appstore/mail.tar.gz -u $FTP_LOGIN:$FTP_PW ftp://ftp.portknox.net/htdocs/mail/mail.tar.gz; fi

matrix:
  include:
    - php: 7.0
      env: "DB=mysql TEST_JS=TRUE"
    - php: 7.0
      env: "DB=pgsql PHP_COVERAGE=TRUE"
    - php: 5.4
      env: "DB=mysql CORE_BRANCH=stable9 PACKAGE=TRUE"
    - php: 5.5
      env: "DB=mysql CORE_BRANCH=stable10"
  fast_finish: true
