name: Packaging
on: pull_request

permissions:
  contents: read

jobs:
  release-tarball:
    runs-on: ubuntu-latest
    name: Build release tarball
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - name: Read package.json node and npm engines version
        uses: skjnldsv/read-package-engines-version-actions@8205673bab74a63eb9b8093402fd9e0e018663a1 # v2.2
        id: versions
      - name: Set up Nextcloud env
        uses: ChristophWurst/setup-nextcloud@fc0790385c175d97e88a7cb0933490de6e990374 # v0.3.2
        with:
          node-version: ${{ steps.versions.outputs.nodeVersion }}
          npm-version: ${{ steps.versions.outputs.npmVersion }}
          tools: 'krankerl'
      - name: Package app
        run: krankerl package
      - uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
        with:
          path: build/artifacts/mail.tar.gz
          if-no-files-found: error
