name: Packaging
on: pull_request

permissions:
  contents: read

jobs:
  release-tarball:
    runs-on: ubuntu-latest
    name: Build release tarball
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - name: Read package.json node and npm engines version
        uses: skjnldsv/read-package-engines-version-actions@8205673bab74a63eb9b8093402fd9e0e018663a1 # v2.2
        id: versions
      - name: Set up Nextcloud env
        uses: ChristophWurst/setup-nextcloud@8bc31fe189b3cb3b44122dede08ce39e8932c554 # v0.3.1
        with:
          node-version: ${{ steps.versions.outputs.nodeVersion }}
          npm-version: ${{ steps.versions.outputs.npmVersion }}
          tools: 'krankerl'
      - name: Package app
        run: krankerl package
      - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        with:
          path: build/artifacts/mail.tar.gz
          if-no-files-found: error
